"""all models

Revision ID: 08cec0ddf387
Revises: 426cef99c026
Create Date: 2021-07-10 17:14:22.814979

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '08cec0ddf387'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'caixas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('valor_inicial', sa.Float(), nullable=True),
        sa.Column('saldo', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'fornecedor',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome_fantasia', sa.String(length=200), nullable=False),
        sa.Column('cnpj', sa.String(length=18), nullable=False),
        sa.Column('telefone', sa.String(length=12), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cnpj'),
        sa.UniqueConstraint('telefone'),
    )
    op.create_table(
        'garcons',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=50), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'mesas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('numero', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'operadores',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=50), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'produtos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('descricao', sa.String(length=200), nullable=False),
        sa.Column('preco', sa.DECIMAL(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'contas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('data', sa.Date(), nullable=False),
        sa.Column('id_caixa', sa.Integer(), nullable=False),
        sa.Column('id_garcom', sa.Integer(), nullable=False),
        sa.Column('id_mesa', sa.Integer(), nullable=False),
        sa.Column('id_forma_pagamento', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['id_caixa'],
            ['caixas.id'],
        ),
        sa.ForeignKeyConstraint(
            ['id_forma_pagamento'],
            ['forma_pagamento.id'],
        ),
        sa.ForeignKeyConstraint(
            ['id_garcom'],
            ['garcons.id'],
        ),
        sa.ForeignKeyConstraint(
            ['id_mesa'],
            ['mesas.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'fornecedor_produto',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('id_produto', sa.Integer(), nullable=False),
        sa.Column('id_fornecedor', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id_fornecedor'],
            ['fornecedor.id'],
        ),
        sa.ForeignKeyConstraint(
            ['id_produto'],
            ['produtos.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'operador_caixa',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('id_operador', sa.Integer(), nullable=False),
        sa.Column('id_caixa', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id_caixa'],
            ['caixas.id'],
        ),
        sa.ForeignKeyConstraint(
            ['id_operador'],
            ['operadores.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'ordem_de_compra',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('id_fornecedor', sa.Integer(), nullable=False),
        sa.Column('data', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id_fornecedor'],
            ['fornecedor.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_foreign_key(None, 'conta_produto', 'contas', ['id_conta'], ['id'])
    op.create_foreign_key(None, 'conta_produto', 'produtos', ['id_produto'], ['id'])
    op.create_foreign_key(None, 'estoque_produto', 'produtos', ['id_produto'], ['id'])
    op.create_foreign_key(
        None, 'produto_ordem_de_compra', 'produtos', ['id_produto'], ['id']
    )
    op.create_foreign_key(
        None, 'produto_ordem_de_compra', 'ordem_de_compra', ['id_ordem'], ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produto_ordem_de_compra', type_='foreignkey')
    op.drop_constraint(None, 'produto_ordem_de_compra', type_='foreignkey')
    op.drop_constraint(None, 'estoque_produto', type_='foreignkey')
    op.drop_constraint(None, 'conta_produto', type_='foreignkey')
    op.drop_constraint(None, 'conta_produto', type_='foreignkey')
    op.drop_table('ordem_de_compra')
    op.drop_table('operador_caixa')
    op.drop_table('fornecedor_produto')
    op.drop_table('contas')
    op.drop_table('produtos')
    op.drop_table('operadores')
    op.drop_table('mesas')
    op.drop_table('garcons')
    op.drop_table('fornecedor')
    op.drop_table('caixas')
    # ### end Alembic commands ###
