"""empty message

Revision ID: 31c489d5d1a3
Revises: cd339a508644
Create Date: 2021-07-22 15:58:15.632056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31c489d5d1a3'
down_revision = 'cd339a508644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_product')
    op.alter_column('accounts', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('purchase_order', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_order', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('accounts', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_table('provider_product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_product', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_provider', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], name='provider_product_id_product_fkey'),
    sa.ForeignKeyConstraint(['id_provider'], ['provider.id'], name='provider_product_id_provider_fkey'),
    sa.PrimaryKeyConstraint('id', name='provider_product_pkey')
    )
    # ### end Alembic commands ###
