"""empty message

Revision ID: 3431de699aa1
Revises: 0fb6bd0d3ff2
Create Date: 2021-07-16 14:27:25.688531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3431de699aa1'
down_revision = '0fb6bd0d3ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('total_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order', 'total_value')
    # ### end Alembic commands ###
