"""empty message

Revision ID: 34c5026fe0de
Revises: a5f1655b0ca1
Create Date: 2021-07-15 12:37:01.866316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c5026fe0de'
down_revision = 'a5f1655b0ca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('id_usuario')
    )
    op.drop_table('gerentes')
    op.drop_constraint('ordem_de_compra_id_manager_fkey', 'ordem_de_compra', type_='foreignkey')
    op.create_foreign_key(None, 'ordem_de_compra', 'managers', ['id_manager'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ordem_de_compra', type_='foreignkey')
    op.create_foreign_key('ordem_de_compra_id_manager_fkey', 'ordem_de_compra', 'gerentes', ['id_manager'], ['id'])
    op.create_table('gerentes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name='gerentes_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id', name='gerentes_pkey'),
    sa.UniqueConstraint('cpf', name='gerentes_cpf_key'),
    sa.UniqueConstraint('id_usuario', name='gerentes_id_usuario_key')
    )
    op.drop_table('managers')
    # ### end Alembic commands ###
