"""Product purchase changes, product cost included

Revision ID: 3f6640208026
Revises: e269f7bbee48
Create Date: 2021-07-19 12:00:20.040624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6640208026'
down_revision = '33d405e7792c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_purchase_order', sa.Column('cost', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_purchase_order', 'cost')
    # ### end Alembic commands ###
