"""Criaçao das tabelas conta_produto, produto e estoque_produto

Revision ID: 4cad96b74ef3
Revises: 5929e81ecfe8
Create Date: 2021-07-09 17:11:30.331962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cad96b74ef3'
down_revision = '5929e81ecfe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('operador_caixa_id_caixa_key', 'operador_caixa', type_='unique')
    op.drop_constraint('operador_caixa_id_operador_key', 'operador_caixa', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('operador_caixa_id_operador_key', 'operador_caixa', ['id_operador'])
    op.create_unique_constraint('operador_caixa_id_caixa_key', 'operador_caixa', ['id_caixa'])
    # ### end Alembic commands ###
