"""empty message

Revision ID: 9a1ee4d66e31
Revises: de688c765664
Create Date: 2021-07-15 12:27:35.807893

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9a1ee4d66e31'
down_revision = 'e4a22ea19e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estoque_produto')
    op.alter_column(
        'conta_produto', 'quantity', existing_type=sa.INTEGER(), nullable=True
    )
    op.add_column('contas', sa.Column('is_finished', sa.Boolean(), nullable=True))
    op.add_column(
        'ordem_de_compra', sa.Column('is_finished', sa.Boolean(), nullable=True)
    )
    op.add_column('produtos', sa.Column('stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'stock')
    op.drop_column('ordem_de_compra', 'is_finished')
    op.drop_column('contas', 'is_finished')
    op.alter_column(
        'conta_produto', 'quantity', existing_type=sa.INTEGER(), nullable=False
    )
    op.create_table(
        'estoque_produto',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('id_produto', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ['id_produto'], ['produtos.id'], name='estoque_produto_id_produto_fkey'
        ),
        sa.PrimaryKeyConstraint('id', name='estoque_produto_pkey'),
        sa.UniqueConstraint('id_produto', name='estoque_produto_id_produto_key'),
    )
    # ### end Alembic commands ###
