"""empty message

Revision ID: a5f1655b0ca1
Revises: f940a96954e3
Create Date: 2021-07-15 12:35:50.233887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f1655b0ca1'
down_revision = 'f940a96954e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordem_de_compra', sa.Column('id_manager', sa.Integer(), nullable=False))
    op.drop_constraint('ordem_de_compra_id_gerente_fkey', 'ordem_de_compra', type_='foreignkey')
    op.create_foreign_key(None, 'ordem_de_compra', 'gerentes', ['id_manager'], ['id'])
    op.drop_column('ordem_de_compra', 'id_gerente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordem_de_compra', sa.Column('id_gerente', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ordem_de_compra', type_='foreignkey')
    op.create_foreign_key('ordem_de_compra_id_gerente_fkey', 'ordem_de_compra', 'gerentes', ['id_gerente'], ['id'])
    op.drop_column('ordem_de_compra', 'id_manager')
    # ### end Alembic commands ###
