"""empty message

Revision ID: d83d79fade83
Revises: 4bb8ccbdb2bf
Create Date: 2021-07-19 17:28:25.969116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83d79fade83'
down_revision = '4bb8ccbdb2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('accounts', 'is_finished')
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('accounts', sa.Column('is_finished', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'status')
    # ### end Alembic commands ###
