"""empty message

Revision ID: de688c765664
Revises: 144ef9fdc259
Create Date: 2021-07-14 18:15:26.891960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de688c765664'
down_revision = '144ef9fdc259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_product', sa.Column(
        'quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_product', 'quantity')
    # ### end Alembic commands ###
