"""Table changes in Caixa, Conta, Conta_produto, Estoque, Ordem_de_compra and Produto

Revision ID: f940a96954e3
Revises: 9a1ee4d66e31
Create Date: 2021-07-15 12:31:59.234412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f940a96954e3'
down_revision = '9a1ee4d66e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordem_de_compra', sa.Column('id_gerente', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ordem_de_compra', 'gerentes', ['id_gerente'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ordem_de_compra', type_='foreignkey')
    op.drop_column('ordem_de_compra', 'id_gerente')
    # ### end Alembic commands ###
